# Generated by Django 4.0.4 on 2022-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=120)),
                ('movie_year', models.CharField(max_length=120)),
                ('movie_director', models.CharField(max_length=120)),
                ('movie_image', models.ImageField(null=True, upload_to='movies_pic')),
            ],
        ),
    ]
